import { Sequelize } from 'sequelize';
import { DEV_ENV, ENVIRONMENT, TEST_ENV } from '../../helper/env';

const CONFIG = ENVIRONMENT
  ? {
    DB_NAME: TEST_ENV.DB_NAME_TEST,
    DB_HOST: TEST_ENV.DB_HOST_TEST,
    DB_USERNAME: TEST_ENV.DB_USERNAME_TEST,
    DB_PASSWORD: TEST_ENV.DB_PASSWORD_TEST,
    DB_PORT: TEST_ENV.SERVER_PORT_TEST,
    FRONTEND_URL: TEST_ENV.FRONTEND_URL,
    JWT_ACCESS_SECRET: TEST_ENV.JWT_ACCESS_SECRET,
  }
  : {
    DB_NAME: DEV_ENV.DB_NAME_DEV,
    DB_HOST: DEV_ENV.DB_HOST_DEV,
    DB_USERNAME: DEV_ENV.DB_USERNAME_DEV,
    DB_PASSWORD: DEV_ENV.DB_PASSWORD_DEV,
    SERVER_PORT: DEV_ENV.SERVER_PORT_DEV,
    DB_PORT: DEV_ENV.PORT_DEV,
    FRONTEND_URL: DEV_ENV.FRONTEND_URL,
    JWT_ACCESS_SECRET: DEV_ENV.JWT_ACCESS_SECRET,
  };

const sequelize = new Sequelize(CONFIG.DB_NAME, CONFIG.DB_USERNAME, CONFIG.DB_PASSWORD, {
  host: CONFIG.DB_HOST,
  dialect: 'mysql',
  port: CONFIG.DB_PORT,
});

export { CONFIG, ENVIRONMENT, sequelize };
